### ISSUE TITLE
Simple_cov reports 0.0% coverage with scout_apm auto_instruments enabled 

### ISSUE THREAD

**Issue by jean-francois-labbe** [simplecov-ruby/simplecov#993]
Hi, this is not really a bug, but I spent a lot of time figuring out what was going on.
This may help someone else.

On a new project I faced a 0.0% coverage report when running
```
➜ DISABLE_BOOTSNAP=true DISABLE_SPRING=true RAILS_ENV=test PARALLEL_WORKERS=1 bundle exec rspec 
...
Finished in 0.03475 seconds (files took 4.11 seconds to load)
3 examples, 0 failures

Coverage report generated for RSpec to project/coverage. 0 / 141 LOC (0.0%) covered.
```
Same with rails test
```
➜ DISABLE_BOOTSNAP=true DISABLE_SPRING=true RAILS_ENV=test PARALLEL_WORKERS=1 bundle exec rails test
Run options: --seed 37964

# Running:
.......

Finished in 0.662081s, 10.5727 runs/s, 13.5935 assertions/s.
7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to project/coverage. 0 / 141 LOC (0.0%) covered.
```

The culprit is [scout_apm auto_instruments](https://scoutapm.com/docs/ruby/configuration#auto_instruments) configured inside `config/scout_apm.yml`
```yml
common: &defaults
  log_level: info
  monitor: true
  auto_instruments: true

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false
```

SimpleCov seems to be incompatible with ScoutApm auto_instrument.
To fix the issue I **turned off auto_instruments** in `test` env inside  `config/scout_apm.yml`
```yml
common: &defaults
  log_level: info
  monitor: true
  auto_instruments: true

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false
  auto_instruments: false
```

```
➜ DISABLE_BOOTSNAP=true DISABLE_SPRING=true RAILS_ENV=test PARALLEL_WORKERS=1 bundle exec rspec 
...

Finished in 0.03196 seconds (files took 4.13 seconds to load)
3 examples, 0 failures

Coverage report generated for RSpec to project/coverage. 36 / 117 LOC (30.77%) covered.
```

```
➜ DISABLE_BOOTSNAP=true DISABLE_SPRING=true RAILS_ENV=test PARALLEL_WORKERS=1 bundle exec rails test
Run options: --seed 28666

# Running:
.......

Finished in 0.558927s, 12.5240 runs/s, 16.1023 assertions/s.
7 runs, 9 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to project/coverage. 50 / 107 LOC (46.73%) covered.
```
